version: '2'
services:
  web:
    build: .
    ports:
      - "5000:5000"
    tty: true
    volumes:
      - C:\Users\tahir.shaukat\Desktop\NLP_SPACY\Docker_compose_mongodb:/counter_app
    links:
      - db:mongodb
    container_name: counterapp_web_2
    depends_on:
      - db

  db:
    image: mongo:3.0.2
    container_name: counter_db_2